In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('movies.csv', index_col=0)
directors = pd.read_csv('directors.csv', index_col = 0)

In [ ]:
movies.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [ ]:
directors.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [ ]:
movies.shape

(1465, 11)

In [ ]:
directors.shape

(2349, 3)

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [ ]:
directors.duplicated().sum()

np.int64(0)

In [ ]:
# How many directors have directed atleast one movie
movies['director_id'].nunique()

199

In [ ]:
movies['day'].value_counts()

day
Friday       654
Thursday     277
Wednesday    276
Tuesday       98
Monday        67
Saturday      47
Sunday        46
Name: count, dtype: int64

In [ ]:
movies['director_id'].duplicated().sum()

np.int64(1266)

In [ ]:
# membership
[2,3] in [1,2,3,4], [1] in [1,2,3], 1 in [1,2,3]

(False, False, True)

In [ ]:
len(movies[movies['director_id'].isin(directors['id'])])

1465

In [3]:
# merge
# Get all the movies data along with their directors

data = movies.merge(directors, how='left', left_on='director_id', right_on='id')

In [ ]:
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male

In [ ]:
data.drop(columns=['id_x', 'id_y'], inplace=True)

In [ ]:
data.head()

,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,gender
0,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,Male
1,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,Male
2,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,Male
3,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,Male
4,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,Male

In [ ]:
movies.describe()

,id,budget,popularity,revenue,vote_average,vote_count,director_id,year
count,1465.000000,1.465000e+03,1465.000000,1.465000e+03,1465.000000,1465.000000,1465.000000,1465.000000
mean,45225.191126,4.802295e+07,30.855973,1.432539e+08,6.368191,1146.396587,5040.192491,2002.615017
std,1189.096396,4.935541e+07,34.845214,2.064918e+08,0.818033,1578.077438,258.059631,8.680141
min,43597.000000,0.000000e+00,0.000000,0.000000e+00,3.000000,1.000000,4762.000000,1976.000000
25%,44236.000000,1.400000e+07,11.000000,1.738013e+07,5.900000,216.000000,4845.000000,1998.000000
50%,45022.000000,3.300000e+07,23.000000,7.578164e+07,6.400000,571.000000,4964.000000,2004.000000
75%,45990.000000,6.600000e+07,41.000000,1.792469e+08,6.900000,1387.000000,5179.000000,2009.000000
max,48395.000000,3.800000e+08,724.000000,2.787965e+09,8.300000,13752.000000,6204.000000,2016.000000

In [ ]:
len(movies[movies['year'].isin([2012])])

49

In [ ]:
movies['year'].isin([2012]).sum()

np.int64(49)

In [ ]:
def encode_gender(val):
  if val['gender'] == 'Male': return 0
  else: return 1

In [ ]:
data['gender_encoded']=data.apply(encode_gender, axis=1)

In [ ]:
data['gender_encoded'].value_counts()

gender_encoded
0    1309
1     156
Name: count, dtype: int64

In [ ]:
data['profit']=data['revenue'] - data['budget']

In [ ]:
data.head()

,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,gender,profit
0,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,0,2550965087
1,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,0,661000000
2,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,0,635674609
3,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,0,834939099
4,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,0,632871626

# Group by

In [ ]:
data.groupby('director_name').groups

{'Adam McKay': [176, 323, 366, 505, 839, 916], 'Adam Shankman': [265, 300, 350, 404, 458, 843, 999, 1231], 'Alejandro González Iñárritu': [106, 749, 1015, 1034, 1077, 1405], 'Alex Proyas': [95, 159, 514, 671, 873], 'Alexander Payne': [793, 1006, 1101, 1211, 1281], 'Andrew Adamson': [11, 43, 328, 501, 947], 'Andrew Niccol': [533, 603, 701, 722, 1439], 'Andrzej Bartkowiak': [349, 549, 754, 911, 924], 'Andy Fickman': [517, 681, 909, 926, 973, 1023], 'Andy Tennant': [314, 320, 464, 593, 676, 885], 'Ang Lee': [99, 134, 748, 840, 1089, 1110, 1132, 1184], 'Anne Fletcher': [610, 650, 736, 789, 1206], 'Antoine Fuqua': [310, 338, 424, 467, 576, 808, 818, 1105], 'Atom Egoyan': [946, 1128, 1164, 1194, 1347, 1416], 'Barry Levinson': [313, 319, 471, 594, 878, 898, 1013, 1037, 1082, 1143, 1185, 1345, 1378], 'Barry Sonnenfeld': [13, 48, 90, 205, 591, 778, 783], 'Ben Stiller': [209, 212, 547, 562, 850], 'Bill Condon': [102, 307, 902, 1233, 1381], 'Bobby Farrelly': [352, 356, 481, 498, 624, 630, 654, 806, 928, 972, 1111], 'Brad Anderson': [1163, 1197, 1350, 1419, 1430], 'Brett Ratner': [24, 39, 188, 207, 238, 292, 405, 456, 920], 'Brian De Palma': [228, 255, 318, 439, 747, 905, 919, 1088, 1232, 1261, 1317, 1354], 'Brian Helgeland': [512, 607, 623, 742, 933], 'Brian Levant': [418, 449, 568, 761, 860, 1003], 'Brian Robbins': [416, 441, 669, 962, 988, 1115], 'Bryan Singer': [6, 32, 33, 44, 122, 216, 297, 1326], 'Cameron Crowe': [335, 434, 488, 503, 513, 698], 'Catherine Hardwicke': [602, 695, 724, 937, 1406, 1412], 'Chris Columbus': [117, 167, 204, 218, 229, 509, 656, 897, 996, 1086, 1129], 'Chris Weitz': [17, 500, 794, 869, 1202, 1267], 'Christopher Nolan': [3, 45, 58, 59, 74, 565, 641, 1341], 'Chuck Russell': [177, 410, 657, 1069, 1097, 1339], 'Clint Eastwood': [369, 426, 447, 482, 490, 520, 530, 535, 645, 727, 731, 786, 787, 899, 974, 986, 1167, 1190, 1313], 'Curtis Hanson': [494, 579, 606, 711, 733, 1057, 1310], 'Danny Boyle': [527, 668, 1083, 1085, 1126, 1168, 1287, 1385], 'Darren Aronofsky': [113, 751, 1187, 1328, 1363, 1458], 'Darren Lynn Bousman': [1241, 1243, 1283, 1338, 1440], 'David Ayer': [50, 273, 741, 1024, 1146, 1407], 'David Cronenberg': [541, 767, 994, 1055, 1254, 1268, 1334], 'David Fincher': [62, 213, 253, 383, 398, 478, 522, 555, 618, 785], 'David Gordon Green': [543, 862, 884, 927, 1376, 1418, 1432, 1459], 'David Koepp': [443, 644, 735, 1041, 1209], 'David Lynch': [583, 1161, 1264, 1340, 1456], 'David O. Russell': [422, 556, 609, 896, 982, 989, 1229, 1304], 'David R. Ellis': [582, 634, 756, 888, 934], 'David Zucker': [569, 619, 965, 1052, 1175], 'Dennis Dugan': [217, 260, 267, 293, 303, 718, 780, 977, 1247], 'Donald Petrie': [427, 507, 570, 649, 858, 894, 1106, 1331], 'Doug Liman': [52, 148, 251, 399, 544, 1318, 1451], 'Edward Zwick': [92, 182, 346, 566, 791, 819, 825], 'F. Gary Gray': [308, 402, 491, 523, 697, 833, 1272, 1380], 'Francis Ford Coppola': [487, 559, 622, 646, 772, 1076, 1155, 1253, 1312], 'Francis Lawrence': [63, 72, 109, 120, 679], 'Frank Coraci': [157, 249, 275, 451, 577, 599, 963], 'Frank Oz': [193, 355, 473, 580, 712, 813, 987], 'Garry Marshall': [329, 496, 528, 571, 784, 893, 1029, 1169], 'Gary Fleder': [518, 667, 689, 867, 981, 1165], 'Gary Winick': [258, 797, 798, 804, 1454], 'Gavin O'Connor': [820, 841, 939, 953, 1444], 'George A. Romero': [250, 1066, 1096, 1278, 1367, 1396], 'George Clooney': [343, 450, 831, 966, 1302], 'George Miller': [78, 103, 233, 287, 1250, 1403, 1450], 'Gore Verbinski': [1, 8, 9, 107, 119, 633, 1040], 'Guillermo del Toro': [35, 252, 419, 486, 1118], 'Gus Van Sant': [595, 1018, 1027, 1159, 1240, 1311, 1398], 'Guy Ritchie': [124, 215, 312, 1093, 1225, 1269, 1420], 'Harold Ramis': [425, 431, 558, 586, 788, 1137, 1166, 1325], 'Ivan Reitman': [274, 643, 816, 883, 910, 935, 1134, 1242], 'James Cameron': [0, 19, 170, 173, 344, 1100, 1320], 'James Ivory': [1125, 1152, 1180, 1291, 1293, 1390, 1397], 'James Mangold': [140, 141, 557, 560, 829, 845, 958, 1145], 'James Wan': [30, 617, 1002, 1047, 1337, 1417, 1424], 'Jan de Bont': [155, 224, 231, 270, 781], 'Jason Friedberg': [812, 1010, 1012, 1014, 1036], 'Jason Reitman': [792, 1092, 1213, 1295, 1299], 'Jaume Collet-Serra': [516, 540, 640, 725, 1011, 1189], 'Jay Roach': [195, 359, 389, 397, 461, 703, 859, 1072], 'Jean-Pierre Jeunet': [423, 485, 605, 664, 765], 'Joe Dante': [284, 525, 638, 1226, 1298, 1428], 'Joe Wright': [85, 432, 553, 803, 814, 855], 'Joel Coen': [428, 670, 691, 707, 721, 889, 906, 980, 1157, 1238, 1305], 'Joel Schumacher': [128, 184, 348, 484, 572, 614, 652, 764, 876, 886, 1108, 1230, 1280], 'John Carpenter': [537, 663, 686, 861, 938, 1028, 1080, 1102, 1329, 1371], 'John Glen': [601, 642, 801, 847, 864], 'John Landis': [524, 868, 1276, 1384, 1435], 'John Madden': [457, 882, 1020, 1249, 1257], 'John McTiernan': [127, 214, 244, 351, 534, 563, 648, 782, 838, 1074], 'John Singleton': [294, 489, 732, 796, 1120, 1173, 1316], 'John Whitesell': [499, 632, 763, 1119, 1148], 'John Woo': [131, 142, 264, 371, 420, 675, 1182], 'Jon Favreau': [46, 54, 55, 382, 759, 1346], 'Jon M. Chu': [100, 225, 810, 1099, 1186], 'Jon Turteltaub': [64, 180, 372, 480, 760, 846, 1171], 'Jonathan Demme': [277, 493, 1000, 1123, 1215], 'Jonathan Liebesman': [81, 143, 339, 1117, 1301], 'Judd Apatow': [321, 710, 717, 865, 881], 'Justin Lin': [38, 123, 246, 1437, 1447], 'Kenneth Branagh': [80, 197, 421, 879, 1094, 1277, 1288], 'Kenny Ortega': [412, 852, 1228, 1315, 1365], 'Kevin Reynolds': [53, 502, 639, 1019, 1059], ...}

In [ ]:
data.groupby('director_name').get_group('Kevin Reynolds')

,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,gender,profit
53,175000000,44,264218220,Waterworld,5.9,992,4814,1995,Jul,Friday,Kevin Reynolds,1,89218220
502,48000000,28,390493908,Robin Hood: Prince of Thieves,6.6,909,4814,1991,Jun,Friday,Kevin Reynolds,1,342493908
639,35000000,26,75395048,The Count of Monte Cristo,7.3,453,4814,2002,Jan,Wednesday,Kevin Reynolds,1,40395048
1019,20000000,16,46069568,Risen,5.7,295,4814,2016,Feb,Friday,Kevin Reynolds,1,26069568
1059,20000000,3,305070,Rapa Nui,6.2,33,4814,1994,Sep,Friday,Kevin Reynolds,1,-19694930

In [ ]:
count = data.groupby('director_name')['title'].count()
count

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: title, Length: 199, dtype: int64

In [ ]:
# which director have directed highest number of movies
data.groupby('director_name')['title'].count().max()

26

In [ ]:
mask = data.groupby('director_name')['title'].count() == data.groupby('director_name')['title'].count().max()
mask

director_name
Adam McKay                     False
Adam Shankman                  False
Alejandro González Iñárritu    False
Alex Proyas                    False
Alexander Payne                False
                               ...
Wes Craven                     False
Wolfgang Petersen              False
Woody Allen                    False
Zack Snyder                    False
Zhang Yimou                    False
Name: title, Length: 199, dtype: bool

In [ ]:
count[mask]

director_name
Steven Spielberg    26
Name: title, dtype: int64

In [ ]:
# Get total budget spent by each director
data.groupby('director_name')['budget'].sum()

director_name
Adam McKay                     341500000
Adam Shankman                  387000000
Alejandro González Iñárritu    200000000
Alex Proyas                    352000000
Alexander Payne                 78000000
                                 ...
Wes Craven                     233800000
Wolfgang Petersen              631000000
Woody Allen                    212000000
Zack Snyder                    860000000
Zhang Yimou                    125000110
Name: budget, Length: 199, dtype: int64

In [ ]:
data.groupby('director_name')['year'].aggregate(['min','max'])

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

# Group based filtering

In [ ]:
# Get details of movie by high budget directors only
data_budget = data.groupby('director_name')['budget'].max().reset_index()
names = data_budget[data_budget['budget'] >= 100000000]
names

                   director_name     budget
0                     Adam McKay  100000000
2    Alejandro González Iñárritu  135000000
3                    Alex Proyas  140000000
5                 Andrew Adamson  225000000
10                       Ang Lee  137000000
..                           ...        ...
187                  Tom Shadyac  175000000
188                   Tom Tykwer  102000000
189                   Tony Scott  100000000
195            Wolfgang Petersen  175000000
197                  Zack Snyder  250000000

[85 rows x 2 columns]

In [ ]:
data[data['director_name'].isin(names['director_name'])]

,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,gender,gender_encoded
0,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,Male,0
1,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,Male,0
2,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,Male,0
3,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,Male,0
4,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,Male,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,400000,33,100000000,Mad Max,6.6,1213,4845,1979,Apr,Thursday,George Miller,Male,0
1451,200000,13,4505922,Swingers,6.8,253,4813,1996,Oct,Friday,Doug Liman,Male,0
1452,0,5,2611555,Three,6.3,31,4936,2010,Dec,Thursday,Tom Tykwer,Male,0
1458,60000,27,3221152,Pi,7.1,586,4881,1998,Jul,Friday,Darren Aronofsky,Male,0
1460,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday,Martin Scorsese,Male,0

In [ ]:
avg_rev_dir = data.groupby('director_name')['revenue'].mean().reset_index()
avg_rev_dir.head(3)

                 director_name       revenue
0                   Adam McKay  1.431794e+08
1                Adam Shankman  1.091953e+08
2  Alejandro González Iñárritu  1.463300e+08

In [ ]:
avg_rev_dir[avg_rev_dir['director_name'] == 'Adam McKay']['revenue']

0    1.431794e+08
Name: revenue, dtype: float64

In [ ]:
def get_risky_movies(row):
  avg_rev = avg_rev_dir[avg_rev_dir['director_name'] == row['director_name']]['revenue'].iloc[0]
  return 1 if row['budget'] > avg_rev else 0

In [ ]:
data['risky'] = data.apply(get_risky_movies, axis=1)

In [ ]:
data['risky'].value_counts()

risky
0    1334
1     131
Name: count, dtype: int64

In [ ]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)

In [ ]:
df

      name gender   income
0     Elon      M  53000.0
1     Jeff      F  28000.0
2     Bill      M  25000.0
3  Falguni      F  44000.0

In [ ]:
res = df.groupby('gender')['income'].mean()

In [ ]:
res1 = pd.DataFrame(res)

In [ ]:
res1

         income
gender
F       36000.0
M       39000.0

In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Rex', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']
})

In [ ]:
df.reset_index?

In [ ]:
res = df.groupby('City')['Age'].max().reset_index()
res

      City  Age
0  Chicago   40
1       LA   30
2       NY   25

In [ ]:
r = res.merge(df, left_on='Age', right_on='Age', how='inner').drop_duplicates(subset=['Age'], keep='last').reset_index(drop=True)

In [ ]:
r.head()

    City_x  Age   Name   City_y
0  Chicago   40  David  Chicago
1       LA   30    Bob       LA
2       NY   25    Rex       NY

In [ ]:
import pandas as pd

data = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df = pd.DataFrame(data)

In [ ]:
def check(name,username):
    return name.lower() in username

df[~(df.apply(lambda x:check(x['name'],x['username']), axis=1))]['userid']

1    10
Name: userid, dtype: int64

In [ ]:
df = pd.read_csv('sales.csv')

In [ ]:
df.head(2)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom

In [ ]:
res = df.groupby('Description')['Quantity'].sum()

In [ ]:
res.sort_values(ascending=False)

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     108545
WHITE HANGING HEART T-LIGHT HOLDER     93050
ASSORTED COLOUR BIRD ORNAMENT          81306
JUMBO BAG RED RETROSPOT                78090
BROCADE RING PURSE                     70700
                                       ...
Unsaleable, destroyed.                -15644
missing                               -16467
printing smudges/thrown away          -19200
given away                            -20000
?                                     -26757
Name: Quantity, Length: 5698, dtype: int64

In [ ]:
df[df['Country'] == 'United Kingdom']['StockCode'].nunique()

5303

In [ ]:
def get_total(vals):
  return vals['Quantity'] * vals['Price']

In [ ]:
df['total'] = df.apply(get_total, axis=1)

In [ ]:
df[df['total'] == df['total'].max()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,total
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.6

In [4]:
data.head(2)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male

In [5]:
mask1 = data['director_name'] == 'James Cameron'
mask2 = data['year'] >= 2005
mask3 = data['year'] <= 2010

In [6]:
data[mask1 & mask2 & mask3]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male

In [29]:
x = data.sort_values('popularity', ascending=False)[:10]
a = x['title'].values
# x.sort_values('vote_average', ascending=False)[1:2]

In [30]:
y = data.sort_values('vote_average', ascending=False)[:10]
b = y['title'].values

In [31]:
np.intersect1d(a,b)

array(['Fight Club', 'Inception', 'Interstellar', 'The Dark Knight'],
      dtype=object)

In [37]:
z = data[data['director_name'] == 'Christopher Nolan']
z.groupby('year')['revenue'].sum().sort_values()

year
2000      39723096
2006     109676311
2002     113714830
2005     374218673
2014     675120017
2010     825532764
2008    1004558444
2012    1084939099
Name: revenue, dtype: int64

In [40]:
data['year'].max()
data['year'].min()

1976

In [43]:
bins = [1970,1980,1990,2000,2010,2020]
labels = [1,2,3,4,5]
data['decade'] = pd.cut(data['year'], bins=bins, labels=labels)
# data['decade'].value_count()

In [44]:
data['decade'].value_counts()

decade
4    644
3    376
5    293
2    126
1     26
Name: count, dtype: int64

In [49]:
data.groupby('year')['title'].count().sort_values()

year
1976     3
1979     4
1978     5
1977     6
1980     8
1983     9
1982    10
1984    10
1981    11
1986    11
1987    12
1991    12
1988    13
1985    14
1989    18
1990    18
1993    18
1992    22
2016    26
1994    31
1995    33
2015    41
1998    45
1996    46
1997    46
2012    49
2014    53
2007    54
2013    57
2003    58
2000    59
2004    61
2001    62
2010    63
1999    64
2009    66
2008    67
2011    67
2002    69
2005    71
2006    73
Name: title, dtype: int64

In [50]:
sd = pd.read_csv('sales.csv')
sd.head(2)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom

In [51]:
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176830 entries, 0 to 176829
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      176830 non-null  object
 1   StockCode    176830 non-null  object
 2   Description  175518 non-null  object
 3   Quantity     176830 non-null  int64
 4   InvoiceDate  176830 non-null  object
 5   Price        176830 non-null  float64
 6   Customer ID  135067 non-null  float64
 7   Country      176830 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 10.8+ MB

In [53]:
sd['InvoiceDate'] = pd.to_datetime(sd['InvoiceDate'])
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176830 entries, 0 to 176829
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      176830 non-null  object
 1   StockCode    176830 non-null  object
 2   Description  175518 non-null  object
 3   Quantity     176830 non-null  int64
 4   InvoiceDate  176830 non-null  datetime64[ns]
 5   Price        176830 non-null  float64
 6   Customer ID  135067 non-null  float64
 7   Country      176830 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 10.8+ MB

In [54]:
sd.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [68]:
string = 'Hi my name is subham'

In [78]:
x = pd.Series(string.split())
x.value_counts().sort_values()

Hi        1
my        1
name      1
is        1
subham    1
Name: count, dtype: int64